# Generated by Django 4.1.4 on 2022-12-09 20:00

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='Введите название бренда', max_length=70, verbose_name='Бренд')),
                ('type', models.CharField(help_text='Введите тип техники', max_length=70, verbose_name='Тип')),
                ('tank_volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем бака')),
                ('seats_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество мест')),
                ('load_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Грузоподъемность')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['brand_name', 'type'],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название предприятия', max_length=70, verbose_name='Имя предприятия')),
                ('address', models.CharField(help_text='Введите адрес предприятия', max_length=70, verbose_name='Адрес предприятия')),
                ('num_of_employee', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Число сотрудников')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'ordering': ['id'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_manufacture', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)], verbose_name='Год выпуска')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег')),
                ('price', models.IntegerField(help_text='Введите стоимость в рублях', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
                ('condition', models.CharField(choices=[('NEW', 'Новое'), ('GOOD', 'Хорошее'), ('WORN', 'С пробегом'), ('BAD', 'Плохое'), ('UNK', 'Неизвестно')], default='UNKNOWN', max_length=7, verbose_name='Состояние')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autopark.brand', verbose_name='Бренд')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autopark.enterprise', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорты',
                'ordering': ['brand', 'year_manufacture', 'price', 'mileage'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ФИО', max_length=70, verbose_name='Имя сотрудника')),
                ('date_of_birthday', models.DateField(verbose_name='Дата рождения')),
                ('residential_address', models.TextField(help_text='Введите адрес места проживания', verbose_name='Адрес')),
                ('phone', models.CharField(max_length=70, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('ACT', 'Занят'), ('NACT', 'Свободен')], default='NACT', max_length=4, null=True, verbose_name='Статус')),
                ('car', models.ForeignKey(blank=True, default='NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autopark.vehicle', verbose_name='Машина')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autopark.enterprise', verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['name'],
            },
        ),
    ]
