# Generated by Django 4.1.4 on 2022-12-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='manager',
            field=models.ManyToManyField(to='autopark.manager', verbose_name='Место работы'),
        ),
    ]
