# Generated by Django 4.1.4 on 2022-12-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0005_alter_enterprise_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autopark.vehicle', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_of_birthday',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
    ]
