# Generated by Django 4.1.4 on 2022-12-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0006_alter_driver_car_alter_driver_date_of_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_of_birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
