# Generated by Django 4.1.4 on 2023-01-10 15:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0008_remove_driver_date_of_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 15, 55, 21, 71255)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_manufacture',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска'),
        ),
    ]
