# Generated by Django 4.1.4 on 2023-01-16 20:01

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0012_alter_enterprise_zoner_alter_vehicle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 16, 20, 1, 51, 376699), null=True),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autopark.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='GPSRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autopark.vehicle')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['car'],
            },
        ),
    ]
