# Generated by Django 4.1.4 on 2023-01-16 20:02

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0013_alter_vehicle_date_route_gpsroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 16, 20, 2, 42, 737122), null=True),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.AddField(
            model_name='routes',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autopark.vehicle'),
        ),
    ]
