# Generated by Django 4.1.4 on 2023-01-16 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0014_routes_alter_vehicle_date_delete_route_routes_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 16, 20, 7, 48, 486289), null=True),
        ),
    ]
