# Generated by Django 4.1.4 on 2023-08-10 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("autopark", "0016_alter_routes_options_alter_vehicle_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routes",
            name="distance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="routes",
            name="finish",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="routes",
            name="max_speed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="routes",
            name="start",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="routes",
            name="step",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 8, 10, 15, 47, 55, 875760),
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.CharField(max_length=120)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="autopark.routes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка",
                "verbose_name_plural": "Точки",
                "ordering": ["-created"],
            },
        ),
    ]
